apiVersion: v1
kind: PersistentVolume
metadata:
  name: alertmanager-pv
spec:
  capacity:
    storage: 10Gi  # PVC가 요청할 수 있는 충분한 크기
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""  # StorageClass가 비어 있으므로 기본값
  hostPath:
    path: "/mnt/data/alertmanager"  # 노드의 디렉토리 경로
  volumeMode: Filesystem
